apiVersion: v2
name: platyplus
description: Platyplus
home: 'https://platy.plus/charts/platyplus.html'
sources:
  - 'https://github.com/platyplus/platyplus/tree/master/charts/platyplus'
  - 'https://github.com/platyplus/platyplus/tree/master/apps/platyplus'
  - 'https://github.com/platyplus/platyplus/tree/master/apps/hasura'
appVersion: 0.1.0
version: 0.1.10
dependencies:
  - name: hasura-backend-plus
    version: 0.2.6
    repository: 'file://../hasura-backend-plus'
    condition: hasura.enabled
  - name: standard-service
    alias: frontend
    version: 0.1.15
    repository: 'file://../standard-service'
    condition: frontend.enabled
keywords:
  - hasura
  - graphql
  - postgresql
  - hasura-backend-plus
  - cms
  - offline-first
  - realtime
  - rxdb
  - react
  - nocode
  - lowcode
