name: Publish artifacts on tag
on:
  push:
    tags:
      - '*'
    paths-ignore:
      - 'apps/documentation/**/*'
jobs:
  nx:
    name: Nx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
          scope: '@platyplus'
      # TODO only if tag is related to an Helm chart
      - name: Install Helm & Push plugin
        run: |
          sudo snap install helm --classic
          helm plugin install https://github.com/chartmuseum/helm-push.git
          helm repo add platyplus https://charts.platy.plus --username "$CHARTMUSEUM_USER" --password "$CHARTMUSEUM_PASSWORD"
        env:
          CHARTMUSEUM_USER: ${{ secrets.CHARTMUSEUM_USER }}
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install NodeJS packages
        run: yarn
      - name: Set project var
        id: vars
        run: echo ::set-output name=project::$(git describe --tags HEAD | grep $2@ | awk -F @ '{ print v$1 }')
      # TODO only if tag is related to a Docker image
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: publish
          projects: ${{ steps.vars.outputs.project }}
          nxCloud: 'true'
        env:
          HELM_EXPERIMENTAL_OCI: 1
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
